NOMBRE_EMPRESA = "Soluciones Financieras Profesionales S.A.S."
DEPARTAMENTO = "Departamento de Cobranzas"
TELEFONO = "(01) 123 4567"
EMAIL_CONTACTO = "cobranza@miempresa.com"
DIRECCION = "Calle 123 #45-67, Lima, Perú"
URL_PAGOS = "www.miempresa.com/pagos"
EMAIL_COMPROBANTES = "pagos@miempresa.com"
ICONO_EMPRESA = "icon/empresa1SF.png"